### ISSUE TITLE
invisible bombs with custom notes enabled 

### ISSUE THREAD

**Issue by YukiDesUwU** [legoandmars/BeatSaberCustomNotes#42]
not sure what braking bombs but when i go to default notes it fixes heres a clip of it happening and heres a log where i replicated the bug. https://clips.twitch.tv/MushyArbitrarySaladMau5-85YssGMXN5ZrW4Iy
[_latest.log](https://github.com/legoandmars/BeatSaberCustomNotes/files/7819591/_latest.log)

**Comment by rithik-b** [comment]
This was already fixed in the latest version (2.5.1)

**Comment by YukiDesUwU** [comment]
downloaded mod for the 3rd time today played a hour ago and bombs still disappear with hmd enabled

**Comment by rithik-b** [comment]
Show the logs again

**Comment by YukiDesUwU** [comment]
[_latest.log](https://github.com/legoandmars/BeatSaberCustomNotes/files/7825566/_latest.log)
heres my latest log. turned hmd on and played song with bombs failed then exited. i have a recording side by side view(headset veiw vs. hmd) as well if needed

**Comment by rithik-b** [comment]
https://github.com/legoandmars/BeatSaberCustomNotes/releases/tag/2.5.1
Seems like the correct file wasn't uploaded when I checked 💀 it is fixed here now

**Comment by YukiDesUwU** [comment]
Sick it’s working now! Actually thought I was going crazy for a sec 💀
