### ISSUE TITLE
Options panel

### ISSUE THREAD

**Issue by laugexd** [legoandmars/BeatSaberCustomNotes#7]
Being able to make different options for notes seems like a good idea to me, you would be able to add some kind of component allowing you to select objects and choose what to do with them. Each of these components will have a name which will show up in-game in the note select menu. There would be several different types of options, like a dropdown list, a checkbox, a radio box, and a text input box. Use cases could be having different variations of the same note, so having all of them in the same file and just choosing the variation from a dropdown. Another use case is a note with a bunch of optional features, you could assign each one to a checkbox for easy control. As for how this could be implemented, there could be an object with a specific name like "Options" which would be the parent of all the other objects holding the components.

**Comment by legoandmars** [comment]
added a while ago, forgot to close
